### ISSUE TITLE
Prepare Database for diary entries

### ISSUE THREAD

**Issue by ingbeck** [ingbeck/TrackMyMeal#6]
**As a Developer** 
**I need** a collection to store data for diary entries
**to be able to** store a diary with entries for every day.

## Acceptance Criteria

- [ ] The Collection exists
- [ ] 1 Example Data exists

## Tasks

(for developers team)

- [ ] Create collection "diaries"
- [ ] Create collection "diaryentries"
