### ISSUE TITLE
Create Startscreen

### ISSUE THREAD

**Issue by ingbeck** [ingbeck/TrackMyMeal#7]
**As a User** 
**I need** a page that shows me what the application is about and how I can log in.

## Acceptance Criteria

- [x] The application name is displayed
- [x] The application logo is displayed

## Tasks

(for developers team)

- [x] Create a React-Route to the Startpage
- [x] Add Title and Logo to the Page
