### ISSUE TITLE
Spike: Login/Registration

### ISSUE THREAD

**Issue by ingbeck** [ingbeck/TrackMyMeal#8]
**As a Developer** 
**I need** to know how to enable OAuth with Google for my project.

## Acceptance Criteria

- [x] I know how to enable OAuth with google for my project.

## Tasks

(for developers team)

- [x] Research the process to activate Google OAuth2.0 for Projects
- [x] Prepare Link to OAuth registration for #7
