### ISSUE TITLE
Login/Registration

### ISSUE THREAD

**Issue by ingbeck** [ingbeck/TrackMyMeal#9]
**As a User** 
**I need** a way to log in 
**to be able to** create a profile and track my calories.

## Acceptance Criteria

- [ ] Login/registration based on OAuth2.0 with GoogleId.
- [ ] When no userprofile exists the user gets redirect to the profile creation process.
- [ ] When the userprofile exisits it is redirected to the homepage. 

## Tasks

(for developers team)

- [ ] TODO: Google with OAuth
- [ ] Implement OAuth2.0 for google accounts
